[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/sgf/*"
  to = "https://raw.githubusercontent.com/gogameguru/go-problems/master/weekly-go-problems/:splat"
  status = 200
  force = true

